# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20171115_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='byline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
