# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('articles', '0005_articlepluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleArticleTeaserPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='articles_singlearticleteaserpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('flavor', models.CharField(choices=[('action', 'Bold headings and action button'), ('link', 'Prominent read-more button'), ('simple', 'Simple')], max_length=8)),
                ('override_title', models.CharField(blank=True, max_length=80)),
                ('override_subtitle', models.CharField(blank=True, max_length=80)),
                ('override_content', djangocms_text_ckeditor.fields.HTMLField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
