# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('articles', '0007_singlearticleteaserpluginmodel_override_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFeedPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='articles_articlefeedpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=40)),
                ('max_articles', models.SmallIntegerField(default=6)),
                ('include_content', models.BooleanField(default=False)),
                ('include_blog', models.BooleanField(default=False)),
                ('include_review', models.BooleanField(default=False)),
                ('include_event', models.BooleanField(default=False)),
                ('include_venue', models.BooleanField(default=False)),
                ('include_profile', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
