# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('articles', '0008_articlefeedpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeedPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='articles_eventfeedpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=40)),
                ('max_articles', models.SmallIntegerField(default=6)),
                ('max_days_ahead', models.SmallIntegerField(default=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
