# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('articles', '0010_auto_20171118_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRelatedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_title', models.CharField(blank=True, max_length=80)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('other_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_article', to='articles.Article')),
            ],
            options={
                'verbose_name_plural': 'Other articles related to this article',
                'verbose_name': 'Other article related to this article',
            },
        ),
        migrations.CreateModel(
            name='ArticleRelatedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_title', models.CharField(blank=True, max_length=80)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page')),
            ],
            options={
                'verbose_name_plural': 'Pages related to this article',
                'verbose_name': 'Page related to this article',
            },
        ),
        migrations.CreateModel(
            name='ArticleRelatedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=80)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
            options={
                'verbose_name_plural': 'URLs related to this article',
                'verbose_name': 'URL related to this article',
            },
        ),
    ]
