# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 13:28
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_articlerelatedarticle_articlerelatedpage_articlerelatedurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True),
        ),
    ]
