# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('articles', '0012_auto_20171122_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Tag name')),
                ('meaning', models.CharField(blank=True, max_length=80, verbose_name='Meaning')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='articlefeedpluginmodel',
            name='tags',
            field=models.ManyToManyField(to='articles.ArticleTag'),
        ),
        migrations.AddField(
            model_name='eventfeedpluginmodel',
            name='tags',
            field=models.ManyToManyField(to='articles.ArticleTag'),
        ),
    ]
