# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20171123_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefeedpluginmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.ArticleTag'),
        ),
        migrations.AlterField(
            model_name='eventfeedpluginmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.ArticleTag'),
        ),
    ]
