# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20171123_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefeedpluginmodel',
            name='override_nothing_found',
            field=models.CharField(blank=True, max_length=120, verbose_name='Use this text instead of "Nothing found"'),
        ),
        migrations.AddField(
            model_name='eventfeedpluginmodel',
            name='override_nothing_found',
            field=models.CharField(blank=True, max_length=120, verbose_name='Use this text instead of "Nothing found"'),
        ),
    ]
