# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20171205_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefeedpluginmodel',
            name='flavor',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Standard article feed design')], default=1),
        ),
        migrations.AddField(
            model_name='eventfeedpluginmodel',
            name='flavor',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Standard article feed design')], default=1),
        ),
    ]
