# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20171206_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='articlefeedpluginmodel',
            name='flavor',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Standard article/event feed design')], default=1),
        ),
        migrations.AlterField(
            model_name='eventfeedpluginmodel',
            name='flavor',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Standard article/event feed design')], default=1),
        ),
    ]
