# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 13:04
from __future__ import unicode_literals

from django.db import migrations


def new_flavor(apps, schema_editor):
    Model = apps.get_model('articles', 'SingleArticleTeaserPluginModel')
    for object in Model.objects.all():
        object.new_flavor = {
            'action': 1,
            'link': 2,
            'simple': 3,
        }[object.flavor]
        object.save()


def old_flavor(apps, schema_editor):
    Model = apps.get_model('articles', 'SingleArticleTeaserPluginModel')
    for object in Model.objects.all():
        object.flavor = {
            1: 'action',
            2: 'link',
            3: 'simple',
        }[object.new_flavor]
        object.save()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_singlearticleteaserpluginmodel_new_flavor'),
    ]

    operations = [
        migrations.RunPython(new_flavor),
        migrations.RunPython(old_flavor),
    ]
