# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_remove_singlearticleteaserpluginmodel_flavor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlearticleteaserpluginmodel',
            old_name='new_flavor',
            new_name='flavor',
        ),
    ]
