# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20171208_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepluginmodel',
            name='flavor',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Standard article design'), (2, 'Record album layout')], default=1),
        ),
    ]
