# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_articlepluginmodel_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creator_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='flavor',
            field=models.CharField(choices=[('content', 'Generic Content'), ('blog', 'Blog article'), ('review', 'Review'), ('event', 'Event'), ('venue', 'Venue'), ('profile', 'Profile'), ('album', 'Album')], max_length=8),
        ),
    ]
