# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_auto_20171222_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefeedpluginmodel',
            name='include_album',
            field=models.BooleanField(default=False),
        ),
    ]
