# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-20 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_articlefeedpluginmodel_include_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfeedpluginmodel',
            name='is_future',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='eventfeedpluginmodel',
            name='max_days_behind',
            field=models.SmallIntegerField(default=0),
        ),
    ]
